### ISSUE TITLE
[website bug] tauri.app is broken on Firefox Focus

### ISSUE THREAD

**Issue by JonahPlusPlus** [tauri-apps/tauri-docs#1350] opened 2023-07-31 17:34 UTC
### Describe the bug

Not an issue with tauri, but with the project website.

When navigating to [tauri.app](tauri.app) in Firefox Focus, it breaks down, saying:
```
Your Docusaurus site did not load properly.
A very common reason is a wrong site baseUrl configuration.
Current configured baseUrl = / (default value)
We suggest trying baseUrl = /
```

The CSS doesn't load, missing up the rest of the site.

Testing the site on mobile via other browsers (Firefox Mobile and Chrome) yields expected results.
I have made a web compat report, but maybe there is something that can be done server side?

### Reproduction

Go to [tauri.app](tauri.app) in Firefox Focus.

### Expected behavior

Regular site behavior.

### Platform and versions

```text
Firefox Focus 115 on Android 11
```

**Comment by FabianLars** [comment] 2023-08-01 17:01
Works fine on my phone 🤔 

Do you maybe have a proxy or something set up either _for_ Focus or everything but Focus? That was so far the only reason for that kind of errors, see https://github.com/tauri-apps/tauri-docs/issues/1234 for example.

Also, can you check `https://beta.tauri.app` too? It's an in-progress rewrite of our whole website not using docusaurus so would be nice to know if it suffers from similar problems.

**Comment by lorenzolewis** [comment] 2023-08-05 15:07
Closing this as we're moving over to a different documentation system anyway.

**Comment by JonahPlusPlus** [comment] 2023-08-08 01:57
> Also, can you check `https://beta.tauri.app` too? It's an in-progress rewrite of our whole website not using docusaurus so would be nice to know if it suffers from similar problems.

Doesn't have any issues, works as intended.

> Do you maybe have a proxy or something set up either _for_ Focus or everything but Focus? That was so far the only reason for that kind of errors, see #1234 for example.

Tried disabling enhanced tracking protection. It seems the "Block other content trackers" option, under "Privacy and Security", was the issue. It appears that part of Docusaurus is marked as a tracker.

**Comment by lorenzolewis** [comment] 2023-08-08 08:01
Oh, that's really awesome to see the root cause (not sure if I'd seen someone dig in that far before). Thank you very much for sharing! <3

**Closed as completed by lorenzolewis** 2023-08-08 08:01 UTC
Labels: bug
