### ISSUE TITLE
[bug] Broken links on Create a Project Page

### ISSUE THREAD

**Issue by gabenddos** [tauri-apps/tauri-docs#2181] opened 2024-05-22 18:54 UTC
### Question you want answered

Access the next steps at end of the Create a Project documentation

### Where did you look for an answer?

In the `Create a Project` documentation there is a Next Steps section at end of page which points to some links.

The second and third are pointing to a broken page:
  [Tauri Command Line Interface (CLI) Reference](https://v2.tauri.app/reference/cli)
  [Learn how to build your Tauri app](https://v2.tauri.app/develop)

![Screenshot 2024-05-22 at 14 52 38](https://github.com/tauri-apps/tauri-docs/assets/36337762/5a1e6124-fd1f-4726-b3e5-e7b09acd4e0f)

### Page URL

https://v2.tauri.app/start/create-project/#next-steps

### Additional context

I've never worked on an open-source project before, but I'm excited to contribute to Tauri!

### Are you willing to work on this yourself?

- [X] I want to work on this myself

**Comment by simonhyll** [comment] 2024-05-22 19:05
Nice catch @gabrielucido! :D
The issue is now assigned to you, the file in question to update would be `src/content/docs/start/create-project.mdx`. Let me know if you need any help getting started, I'm easiest to reach on Discord :)

**Comment by gabenddos** [comment] 2024-05-22 19:18
Locally it seems to be working. So I got back to the PRD docs and also was working. In fact, I had the old broken tab still open in my browser. As soon I took this print the page auto refreshed and it was all working.

![Image](https://github.com/tauri-apps/tauri-docs/assets/36337762/d57b236b-b006-498f-9568-959cb2f11ac7)

I guess someone else fixed or some black magic

**Comment by gabenddos** [comment] 2024-05-22 19:22
Never mind, I think I got it. The missing append slash is breaking the docs in production.
This shouldn't be fixed in a NGINX config or something?

For now, I will add the append slashes as a workaround for this

**Comment by simonhyll** [comment] 2024-05-22 19:59
The weird thing is that it's supposed to work already because the default option for Astro when it comes to trailing slashes is to ignore them, as in match the route whether it exists or not 🤔

But in general I think we consider it to be cleaner to use a trailing slash anyway (for some reason) so I wouldn't necessarily call it just a workaround but a fix :) Thanks!

**Closed as completed** 2024-05-22 19:59 UTC
Labels: bug
