### ISSUE TITLE
More specific directions on user guide walkthrough

### ISSUE THREAD

**Issue by skishlin** [tauri-apps/tauri-docs#790] opened 2022-07-21 10:24 UTC
Hi,

I'm working on making videos/a user guide of using Tauri for absolute beginners. I'm pretty raw when it comes to computer coding and web development, but I spent the last 2 years teaching myself Data Analytics, Python and SQL and I've been learning Rust since February.  The user guide I have in mind is for people coming to the programming/development world with a very limited knowledge base like myself who might be coming to Tauri either for amateur recreation, or as a necessity for work-related projects and need a more layman (see: Troglodyte) approach to utilize it quickly and efficiently for a project they might be working on. 

I noticed that the guide, while informative about the various options available to create the front and backend framework using CLI, doesn't specify that the various methods are either or, rather than steps to be followed sequentially.  I will be filing a PR. 

Thanks

**Comment by FabianLars** [comment] 2022-09-08 15:50
I'll close this as a duplicate of #781, even tho it's slightly different, but at least now the 2 issues are linked to each which should be enough for us to track it.

**Closed as completed by FabianLars** 2022-09-08 15:50 UTC
